name: BUILD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup_env
      run: ./scripts/ci_env_setup.sh 
    - name: installdep
      run: ./scripts/installdep.sh
    - name: build
      run: ./scripts/buildall.sh
